import { useEffect, useMemo, useState } from 'react';
import { Routes, Route, Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowRight, Check, ChefHat, Clock3, LogOut, MapPin, Minus, Plus, Search, ShoppingBag, Star, UtensilsCrossed } from 'lucide-react';
import { api } from './api';
import type { CartLine, Restaurant, User } from './types';

function App(){
 const [cart,setCart]=useState<CartLine[]>([]); const [cartRestaurant,setCartRestaurant]=useState<Restaurant|null>(null);
 const [user,setUser]=useState<User|null>(()=>JSON.parse(localStorage.getItem('foodhub_user')||'null'));
 const count=cart.reduce((n,x)=>n+x.quantity,0);
 const logout=()=>{localStorage.removeItem('foodhub_token');localStorage.removeItem('foodhub_user');setUser(null)};
 return <><header><Link className="brand" to="/"><span><ChefHat/></span>FoodHub</Link><nav><Link to="/">Restaurants</Link>{user&&<Link to="/orders">My orders</Link>}{user?.role==='admin'&&<Link to="/admin">Admin</Link>}</nav><div className="header-actions">{user?<button className="ghost" onClick={logout}><LogOut size={17}/> Sign out</button>:<Link className="ghost link-button" to="/login">Sign in</Link>}<Link className="cart-button" to="/checkout"><ShoppingBag size={18}/> Cart <b>{count}</b></Link></div></header>
 <main><Routes><Route path="/" element={<Home/>}/><Route path="/restaurant/:id" element={<RestaurantPage cart={cart} setCart={setCart} cartRestaurant={cartRestaurant} setCartRestaurant={setCartRestaurant}/>}/><Route path="/login" element={<Auth mode="login" setUser={setUser}/>}/><Route path="/register" element={<Auth mode="register" setUser={setUser}/>}/><Route path="/checkout" element={<Checkout cart={cart} restaurant={cartRestaurant} user={user} clear={()=>{setCart([]);setCartRestaurant(null)}}/>}/><Route path="/orders" element={<Orders user={user}/>}/><Route path="/admin" element={<Admin user={user}/>}/></Routes></main><footer><div className="brand footer-brand"><span><ChefHat/></span>FoodHub</div><p>A portfolio MERN application built with React, TypeScript, Express, MongoDB and Docker.</p></footer></>;
}

function Home(){const [items,setItems]=useState<Restaurant[]>([]);const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);useEffect(()=>{api<Restaurant[]>('/restaurants').then(setItems).finally(()=>setLoading(false))},[]);const visible=items.filter(r=>(r.name+' '+r.cuisine.join(' ')).toLowerCase().includes(search.toLowerCase()));return <>
 <section className="hero"><div className="hero-copy"><span className="eyebrow">LOCAL FAVORITES, DELIVERED</span><h1>Your next favorite meal is closer than you think.</h1><p>Discover neighborhood kitchens, build your order and track every step from checkout to your door.</p><label className="search"><Search/><input aria-label="Search restaurants" placeholder="Search by restaurant or cuisine" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="trust"><span><Check/> Curated restaurants</span><span><Check/> Secure checkout</span><span><Check/> Live order status</span></div></div><div className="hero-art"><div className="plate"><UtensilsCrossed/><b>Dinner<br/>made easy.</b></div><span className="floating-card"><Clock3/> 25–35 min</span></div></section>
 <section className="restaurant-section"><div className="section-head"><div><span className="eyebrow">EXPLORE NEARBY</span><h2>Restaurants you’ll love</h2></div><span>{visible.length} places</span></div>{loading?<div className="empty">Loading restaurants…</div>:<div className="restaurant-grid">{visible.map(r=><Link className="restaurant-card" to={`/restaurant/${r._id}`} key={r._id}><div className="restaurant-image" style={{backgroundImage:`linear-gradient(180deg, transparent 55%, rgba(0,0,0,.48)), url(${r.imageUrl})`}}><span>{r.cuisine[0]}</span></div><div className="card-body"><div><h3>{r.name}</h3><p>{r.description}</p></div><div className="meta"><span><Star fill="currentColor"/> {r.rating}</span><span><Clock3/> {r.deliveryTime}</span><span>${r.deliveryFee.toFixed(2)} delivery</span></div></div></Link>)}</div>}</section></>}

function RestaurantPage({cart,setCart,cartRestaurant,setCartRestaurant}:{cart:CartLine[];setCart:(x:CartLine[])=>void;cartRestaurant:Restaurant|null;setCartRestaurant:(r:Restaurant)=>void}){const {id}=useParams();const [r,setR]=useState<Restaurant|null>(null);useEffect(()=>{api<Restaurant>(`/restaurants/${id}`).then(setR)},[id]);if(!r)return <div className="empty">Loading menu…</div>;const add=(item:Restaurant['menu'][number])=>{if(cartRestaurant&&cartRestaurant._id!==r._id&&!confirm('Start a new cart from this restaurant?'))return;const current=cartRestaurant?cart:[];const found=current.find(x=>x.item._id===item._id);setCart(found?current.map(x=>x.item._id===item._id?{...x,quantity:x.quantity+1}:x):[...current,{item,quantity:1}]);setCartRestaurant(r)};return <section><div className="restaurant-banner" style={{backgroundImage:`linear-gradient(90deg,rgba(11,24,20,.86),rgba(11,24,20,.25)),url(${r.imageUrl})`}}><div><span className="eyebrow">{r.cuisine.join(' · ')}</span><h1>{r.name}</h1><p>{r.description}</p><div className="banner-meta"><span><Star/> {r.rating}</span><span><Clock3/> {r.deliveryTime}</span><span><MapPin/> ${r.deliveryFee.toFixed(2)} delivery</span></div></div></div><div className="menu-wrap"><div className="section-head"><div><span className="eyebrow">ORDER YOUR FAVORITES</span><h2>Menu</h2></div></div><div className="menu-grid">{r.menu.map(item=><article className="menu-item" key={item._id}><div><span className="menu-category">{item.category}</span><h3>{item.name}</h3><p>{item.description}</p><strong>${item.price.toFixed(2)}</strong></div><button onClick={()=>add(item)} aria-label={`Add ${item.name}`}><Plus/> Add</button></article>)}</div></div></section>}

function Auth({mode,setUser}:{mode:'login'|'register';setUser:(u:User)=>void}){const nav=useNavigate();const [form,setForm]=useState({name:'',email:'',password:''});const [error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const data=await api<{token:string;user:User}>(`/auth/${mode}`,{method:'POST',body:JSON.stringify(form)});localStorage.setItem('foodhub_token',data.token);localStorage.setItem('foodhub_user',JSON.stringify(data.user));setUser(data.user);nav('/')}catch(e){setError((e as Error).message)}};return <div className="auth-shell"><form className="auth-card" onSubmit={submit}><span className="auth-icon"><ChefHat/></span><span className="eyebrow">WELCOME TO FOODHUB</span><h1>{mode==='login'?'Sign in to continue':'Create your account'}</h1><p>{mode==='login'?'Access your orders and checkout faster.':'Save your details and track every order.'}</p>{mode==='register'&&<label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="error">{error}</div>}<button className="primary" type="submit">{mode==='login'?'Sign in':'Create account'} <ArrowRight/></button><small>{mode==='login'?<>New here? <Link to="/register">Create an account</Link></>:<>Already have an account? <Link to="/login">Sign in</Link></>}</small></form></div>}

function Checkout({cart,restaurant,user,clear}:{cart:CartLine[];restaurant:Restaurant|null;user:User|null;clear:()=>void}){const nav=useNavigate();const [address,setAddress]=useState({street:'',city:'',state:'AL',zipCode:''});const [error,setError]=useState('');const subtotal=cart.reduce((s,x)=>s+x.item.price*x.quantity,0);const place=async()=>{if(!user)return nav('/login');try{await api('/orders',{method:'POST',body:JSON.stringify({restaurantId:restaurant?._id,items:cart.map(x=>({menuItemId:x.item._id,quantity:x.quantity})),deliveryAddress:address})});clear();nav('/orders')}catch(e){setError((e as Error).message)}};if(!cart.length)return <div className="empty"><ShoppingBag/><h2>Your cart is empty</h2><p>Add something delicious from a nearby restaurant.</p><Link className="primary link-button" to="/">Browse restaurants</Link></div>;return <section className="checkout"><div><span className="eyebrow">FINAL STEP</span><h1>Checkout</h1><h2>Delivery address</h2><div className="address-grid"><label>Street<input value={address.street} onChange={e=>setAddress({...address,street:e.target.value})}/></label><label>City<input value={address.city} onChange={e=>setAddress({...address,city:e.target.value})}/></label><label>State<input maxLength={2} value={address.state} onChange={e=>setAddress({...address,state:e.target.value.toUpperCase()})}/></label><label>ZIP code<input value={address.zipCode} onChange={e=>setAddress({...address,zipCode:e.target.value})}/></label></div></div><aside className="order-card"><h2>Your order</h2><p>{restaurant?.name}</p>{cart.map(x=><div className="order-line" key={x.item._id}><span>{x.quantity} × {x.item.name}</span><b>${(x.item.price*x.quantity).toFixed(2)}</b></div>)}<hr/><div className="order-line"><span>Subtotal</span><b>${subtotal.toFixed(2)}</b></div><div className="order-line"><span>Delivery</span><b>${restaurant?.deliveryFee.toFixed(2)}</b></div><div className="order-line total"><span>Total</span><b>${(subtotal+(restaurant?.deliveryFee??0)).toFixed(2)}</b></div>{error&&<div className="error">{error}</div>}<button className="primary" onClick={place}>Place order <ArrowRight/></button></aside></section>}

function Orders({user}:{user:User|null}){const [orders,setOrders]=useState<any[]>([]);useEffect(()=>{if(user)api<any[]>('/orders/mine').then(setOrders)},[user]);if(!user)return <div className="empty"><h2>Sign in to see your orders</h2><Link className="primary link-button" to="/login">Sign in</Link></div>;return <section className="narrow"><span className="eyebrow">ORDER HISTORY</span><h1>Your orders</h1>{orders.map(o=><article className="history-card" key={o._id}><div><h3>{o.restaurant?.name}</h3><p>{new Date(o.createdAt).toLocaleString()} · {o.items.length} items</p></div><div><span className={`status ${o.status}`}>{o.status.replaceAll('_',' ')}</span><strong>${o.total.toFixed(2)}</strong></div></article>)}{!orders.length&&<div className="empty">No orders yet.</div>}</section>}

function Admin({user}:{user:User|null}){const [orders,setOrders]=useState<any[]>([]);const load=()=>api<any[]>('/admin/orders').then(setOrders);useEffect(()=>{if(user?.role==='admin')load()},[user]);if(user?.role!=='admin')return <div className="empty"><h2>Admin access required</h2><p>Use the seeded administrator account for the demo.</p></div>;const update=async(id:string,status:string)=>{await api(`/admin/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});load()};return <section className="narrow"><span className="eyebrow">OPERATIONS CONSOLE</span><h1>Manage orders</h1><div className="admin-list">{orders.map(o=><article className="admin-row" key={o._id}><div><h3>{o.restaurant?.name}</h3><p>{o.customer?.name} · ${o.total.toFixed(2)}</p></div><select value={o.status} onChange={e=>update(o._id,e.target.value)}>{['placed','confirmed','preparing','out_for_delivery','delivered','cancelled'].map(s=><option key={s}>{s}</option>)}</select></article>)}</div></section>}
export default App;
